config/routes.rb
Rails.application.routes.draw do
  root to: 'home#top'
  get "/home/about" => "home#about", as: "home_about"
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :edit, :show, :update]
  resources :books, except: :new
  


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :books, dependent: :destroy
  attachment :profile_image
  validates :name, presence: true, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:top, :about]

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def show
    @book = Book.new
    @book_detail = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(params[:id])
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = current_user
    @book = Book.new
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_user_info.html.erb
<div class="col-md-3 mb-4">
  <h2>User info</h2>
  <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>

  <table class="table mb-5">
    <tbody>
      <tr>
        <th>name</th>
        <td><%= user.name %></td>
      </tr>
      <tr>
        <th>introduction</th>
        <td><%= user.introduction %></td>
      </tr>
    </tbody>
  </table>

  <div class="row">
    <%= link_to "" , edit_user_path(user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
  </div>

  <h2 class="mt-3">New book</h2>
  <%= form_with model: book, local: true do |f| %>
    <div class="form-group">
      <label for="book_title" class="d-block">Title</label>
      <%= f.text_field :title, class: "form-control book_title" %>
    </div>
    <div class="form-group">
      <label for="book_opinion" class="d-block">Opinion</label>
      <%= f.text_area :body, class: "form-control book_opinion" %>
    </div>
      <%= f.submit class: "btn btn-success" %>
  <% end %>

</div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-5 col-md-8 col-sm-12 mx-auto">
      <h1>Editing Book</h1>
      
      <%= render "layouts/error_messages", user: @book %>
      
      <%= form_with model: @book, local: true do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, class: "form-control book_title" %>
        </div>
        <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, class: "form-control book_opinion" %>
        </div>
          <%= f.submit class: "btn btn-success" %>
      <% end %>
      <div class="mt-3">
        <%= link_to "Show", book_path(@book), class: "mr-1" %>|
        <%= link_to "Back", books_path, class: "ml-1" %>
      </div>

    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
    
  <%= render "layouts/error_messages", user: @book %>
  
  <div class="row">

    <%= render "books/user_info", user: @user, book: @book %>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>

        <tbody>
          <% @books.each do |books| %>
            <tr>
              <td>
                <%= link_to user_path(books.user) do %>
                  <%= attachment_image_tag books.user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %>
                <% end %>
              </th>
              <td><%= link_to "#{books.title}", book_path(books) %></td>
              <td><%= books.body %></td>
            </tr>
          <% end %>
        </tbody>

      </table>
    </div>

  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

    <%= render "books/user_info", user: @book_detail.user, book: @book %>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <th>
              <%= link_to user_path(@book_detail.user) do %>
                <%= attachment_image_tag @book_detail.user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
                <br>
                <%= @book_detail.user.name  %>
              <% end %>
            </th>
            <td><%= link_to "#{@book_detail.title}", book_path(@book_detail) %></td>
            <td><%= @book_detail.body %></td>
            <% if @book_detail.user == current_user %>
              <td><%= link_to "Edit", edit_book_path(@book_detail), class: "btn btn-success btn-sm" %></td>
              <td><%= link_to "Destroy", book_path(@book_detail), method: :delete, class: "btn btn-danger btn-sm" %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>

  </div>
</div>

app/views/home/about.html.erb
<div class="container">
    <div class="col-lg-7 col-sm-9 col-10 mx-auto text-center mt-3">
      <h1>Welcome to <i class="fas fa-book"></i>Bookers!</h1>
    </div>
</div>

app/views/home/top.html.erb
<div class="container">

    <div class="col-lg-7 col-sm-9 col-10 mx-auto mt-3">
      <div class="pl-3">
        <h1>welcome to <i class="fas fa-book"></i>Bookers !!</h1>
        <p>In <i class="fas fa-book"></i>Bookers,</p>
        <p>you can share and exchange your opinions , inpressions , and emotions</p>
        <p>about various books!</p>
      </div>
      <div class="col-10 mx-auto">
        <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-block mb-3" %>
        <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success btn-block" %>
      </div>
    </div>

</div>

app/views/layouts/_error_messages.html.erb
<div class="text-danger">
  <% if user.errors.any? %>
  　<h3>
      <%= user.errors.count %>errors prohibited this obj from being saved:
    </h3>
    <% user.errors.full_messages.each do |message| %>
      <ul>
        <li>
        <%= message %>
        </li>
      </ul>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> 

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="/">Bookers</a>
        
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarToggleExternalContent">
          <% if user_signed_in? %>
            <ul class="navbar-nav ml-auto">
              <li class="mr-1">
                <%= link_to "Home", user_path(current_user), class: "fas fa-home nav-link text-light" %>
              </li class="mr-1">
              <li>
                <%= link_to "Users", users_path, class: "fas fa-users nav-link text-light" %>
              </li>
              <li class="mr-1">
                <%= link_to "Books", books_path, class: "fas fa-book-open nav-link text-light" %>
              </li>
              <li>
                <%= link_to "logout", destroy_user_session_path, class: "fas fa-sign-out-alt nav-link text-light", method: :delete %>
              </li>
            </ul>
          <% else %>
            <ul class="navbar-nav ml-auto">
              <li class="mr-1">
               <%= link_to "Home", root_path, class: "fas fa-home nav-link text-light" %>
              </li class="mr-1">
              <li>
                <%= link_to "About", home_about_path, class: "fas fa-link nav-link text-light" %>
              </li>
              <li class="mr-1">
                <%= link_to "sign up", new_user_registration_path, class: "fas fa-user-plus nav-link text-light" %>
              </li>
              <li>
                <%= link_to "login", new_user_session_path, class: "fas fa-sign-in-alt nav-link text-light" %>
              </li>
            </ul>
              
          <% end %>
        </div>
        
      </div>
    </nav>
    
    <% if flash[:notice] %>
      <p id="notice"><%= flash[:notice] %></p>
    <% else %>
      <p id="notice"></p>
    <% end %>

    <%= yield %>
    
    <footer>
      <div class="container mt-5">
        <div class="row">
          <p class="mx-auto">
            CopyRight Infratop.inc
            
          </p>
        </div>
      </div>
    </footer>
    
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-5 col-md-8 col-sm-12 mx-auto">
      <h2>User info</h2>
      
      <%= render "layouts/error_messages", user: @user %>
      
      <%= form_with model: @user, local: true do |f| %>
        <div class="form-group">
          <label for="user_name">Name</label>
          <%= f.text_field :name, class:"form-control user_name" %>
        </div>
        <div class="form-group">
          <label for="user_image" class="d-block">Image</label>
          <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
        </div>
        <div class="form-group">
          <label for="user_introduction" class="d-block">Introduction</label>
          <%= f.text_area :introduction, class: "form-control user_introduction" %>
        </div>
          <%= f.submit "Update User", class: "btn btn-secondary" %>
      <% end %>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    
    <%= render "books/user_info", user: @user, book: @book %>

    <div class="col-md-8 offset-md-1">
      <h2> Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th class="col-2">image</th>
            <th class="co-4">name</th>
            <th class="col-2"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td><%= attachment_image_tag user, :profile_image, size: "40x40", fallback: "no_image.jpg" %></td>
            <td><%= user.name %></td>
            <td><%= link_to "Show", user_path(user) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>

    </div>

  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

    <%= render "books/user_info", user: @user, book: @book %>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @user.books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user) do %>
                <%= attachment_image_tag book.user, :profile_image, size: "40x40", fallback: "no_image.jpg" %>
              <% end %>
            </td>
            <td><%= link_to "#{book.title}", book_path(book) %></td>
            <td><%= book.body %></td>
          </tr>
          <% end %>

        </tbody>
      </table>
    </div>

  </div>
</div>